/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.openvnc {

using System;
using System.Runtime.InteropServices;

public class OpenVNCWRAP {
  public static readonly int NULL = OpenVNCWRAPPINVOKE.NULL_get();
  public static readonly int OVNC_HAVE_POLL = OpenVNCWRAPPINVOKE.OVNC_HAVE_POLL_get();
  public static readonly int OVNC_USE_POLL = OpenVNCWRAPPINVOKE.OVNC_USE_POLL_get();
  public static readonly int OVNC_HAVE_IFADDRS = OpenVNCWRAPPINVOKE.OVNC_HAVE_IFADDRS_get();
  public static readonly int OVNC_HAVE_DNS_H = OpenVNCWRAPPINVOKE.OVNC_HAVE_DNS_H_get();
  public static readonly int OVNC_HAVE_SS_LEN = OpenVNCWRAPPINVOKE.OVNC_HAVE_SS_LEN_get();
  public static readonly int OVNC_HAVE_SA_LEN = OpenVNCWRAPPINVOKE.OVNC_HAVE_SA_LEN_get();
  public static readonly int OVNC_HAVE_GETTIMEOFDAY = OpenVNCWRAPPINVOKE.OVNC_HAVE_GETTIMEOFDAY_get();
  public static readonly int OVNC_CONFIG_SERVER_PORT = OpenVNCWRAPPINVOKE.OVNC_CONFIG_SERVER_PORT_get();
  public static readonly int OVNC_CONFIG_CLIENT_PORT = OpenVNCWRAPPINVOKE.OVNC_CONFIG_CLIENT_PORT_get();
  public static readonly int OVNC_CONFIG_VERSION_MAJOR = OpenVNCWRAPPINVOKE.OVNC_CONFIG_VERSION_MAJOR_get();
  public static readonly int OVNC_CONFIG_VERSION_MINOR = OpenVNCWRAPPINVOKE.OVNC_CONFIG_VERSION_MINOR_get();
  public static readonly int OVNC_CONFIG_VERSION_MAJOR_MIN = OpenVNCWRAPPINVOKE.OVNC_CONFIG_VERSION_MAJOR_MIN_get();
  public static readonly int OVNC_CONFIG_VERSION_MINOR_MIN = OpenVNCWRAPPINVOKE.OVNC_CONFIG_VERSION_MINOR_MIN_get();
  public static readonly int OVNC_CONFIG_VERSION_MAJOR_MAX = OpenVNCWRAPPINVOKE.OVNC_CONFIG_VERSION_MAJOR_MAX_get();
  public static readonly int OVNC_CONFIG_VERSION_MINOR_MAX = OpenVNCWRAPPINVOKE.OVNC_CONFIG_VERSION_MINOR_MAX_get();
  public static readonly int OVNC_NET_INVALID_SOCKET = OpenVNCWRAPPINVOKE.OVNC_NET_INVALID_SOCKET_get();
  public static readonly int OVNC_NET_INVALID_FD = OpenVNCWRAPPINVOKE.OVNC_NET_INVALID_FD_get();
  public static readonly int OVNC_NET_SOCKET_HOST_ANY = OpenVNCWRAPPINVOKE.OVNC_NET_SOCKET_HOST_ANY_get();
  public static readonly int OVNC_NET_SOCKET_PORT_ANY = OpenVNCWRAPPINVOKE.OVNC_NET_SOCKET_PORT_ANY_get();
  public static readonly int OVNC_NET_CONNECT_TIMEOUT = OpenVNCWRAPPINVOKE.OVNC_NET_CONNECT_TIMEOUT_get();
  public static readonly int OVNC_NET_MAX_FDS = OpenVNCWRAPPINVOKE.OVNC_NET_MAX_FDS_get();
  public static readonly int OVNC_NET_RCVBUF_SIZE = OpenVNCWRAPPINVOKE.OVNC_NET_RCVBUF_SIZE_get();
  public static readonly int OVNC_NET_SNDBUF_SIZE = OpenVNCWRAPPINVOKE.OVNC_NET_SNDBUF_SIZE_get();
  public static readonly int OVNC_RFB_RECTANGLE_HEADER_SIZE = OpenVNCWRAPPINVOKE.OVNC_RFB_RECTANGLE_HEADER_SIZE_get();
  public static readonly int OVNC_RFB_PIXELFORMAT_SIZE = OpenVNCWRAPPINVOKE.OVNC_RFB_PIXELFORMAT_SIZE_get();
  public static readonly int OVNC_RFB_ZRLE_TILE_WIDTH = OpenVNCWRAPPINVOKE.OVNC_RFB_ZRLE_TILE_WIDTH_get();
  public static readonly int OVNC_RFB_ZRLE_TILE_HEIGHT = OpenVNCWRAPPINVOKE.OVNC_RFB_ZRLE_TILE_HEIGHT_get();
}

}
