/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.openvnc {

public enum vncClientState_t {
  vncClientState_None = 0,
  vncClientState_Configured,
  vncClientState_Started,
  vncClientState_Connecting,
  vncClientState_Connected,
  vncClientState_ProtocolVersionNegotiated,
  vncClientState_SecurityNegotiating,
  vncClientState_SecurityChallenging,
  vncClientState_SecurityChallenged,
  vncClientState_SessionEstablished,
  vncClientState_Disconnected,
  vncClientState_Terminated
}

}
