/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.openvnc {

public enum vncError_t {
  vncError_Success = 0,
  vncError_Ok = vncError_Success,
  vncError_NotImplemented,
  vncError_InvalidParameter,
  vncError_InvalidState,
  vncError_InvalidData,
  vncError_TooShort,
  vncError_SystemError,
  vncError_ApplicationError,
  vncError_3rdApplicationError,
  vncError_MemoryAllocFailed,
  vncError_BufferOverflow,
  vncError_NetworkError
}

}
