/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.openvnc {

public enum vncNetIPVersion_t {
  vncNetIPVersion_None = 0x00,
  vncNetIPVersion_IPv4 = 0x01 << 0,
  vncNetIPVersion_IPv6 = 0x01 << 1,
  vncNetIPVersion_IPv4and6 = vncNetIPVersion_IPv4|vncNetIPVersion_IPv6
}

}
