/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.openvnc {

public enum vncRfbClientMsg_t {
  vncRfbClientMsg_SetPixelFormat = 0,
  vncRfbClientMsg_SetEncodings = 2,
  vncRfbClientMsg_FramebufferUpdateRequest = 3,
  vncRfbClientMsg_KeyEvent = 4,
  vncRfbClientMsg_PointerEvent = 5,
  vncRfbClientMsg_ClientCutText = 6,
  vncRfbClientMsg_Anthony_Liguori = 255,
  vncRfbClientMsg_gii = 253,
  vncRfbClientMsg_tight = 252,
  vncRfbClientMsg_Pierre_Ossman_SetDesktopSize = 251,
  vncRfbClientMsg_Colin_Dean_xvp = 250,
  vncRfbClientMsg_OLIVE_Call_Control = 249
}

}
