/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.openvnc {

public enum vncRfbPixelReaderType_t {
  vncRfbPixelReaderType_C,
  vncRfbPixelReaderType_8bits,
  vncRfbPixelReaderType_16bits,
  vncRfbPixelReaderType_32bits
}

}
