/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.openvnc {

public enum vncRfbSize_t {
  vncRfbSize_Zero = 0,
  vncRfbSize_ProtocolVersion = 12,
  vncRfbSize_SecurityResult = 4,
  vncRfbSize_VNCAuthChallenge = 16,
  vncRfbSize_SetPixelFormat = 20,
  vncRfbSize_FramebufferUpdateRequest = 10
}

}
