/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.openvnc {

public enum vncRfbSecurityResult_t {
  vncRfbSecurityResult_Ok = 0,
  vncRfbSecurityResult_Failed = 1
}

}
