/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.openvnc {

using System;
using System.Runtime.InteropServices;

public class vncRfbRectangle_t : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vncRfbRectangle_t(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(vncRfbRectangle_t obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~vncRfbRectangle_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        OpenVNCWRAPPINVOKE.delete_vncRfbRectangle_t(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public ushort x_position {
    set {
      OpenVNCWRAPPINVOKE.vncRfbRectangle_t_x_position_set(swigCPtr, value);
    } 
    get {
      ushort ret = OpenVNCWRAPPINVOKE.vncRfbRectangle_t_x_position_get(swigCPtr);
      return ret;
    } 
  }

  public ushort y_position {
    set {
      OpenVNCWRAPPINVOKE.vncRfbRectangle_t_y_position_set(swigCPtr, value);
    } 
    get {
      ushort ret = OpenVNCWRAPPINVOKE.vncRfbRectangle_t_y_position_get(swigCPtr);
      return ret;
    } 
  }

  public ushort width {
    set {
      OpenVNCWRAPPINVOKE.vncRfbRectangle_t_width_set(swigCPtr, value);
    } 
    get {
      ushort ret = OpenVNCWRAPPINVOKE.vncRfbRectangle_t_width_get(swigCPtr);
      return ret;
    } 
  }

  public ushort height {
    set {
      OpenVNCWRAPPINVOKE.vncRfbRectangle_t_height_set(swigCPtr, value);
    } 
    get {
      ushort ret = OpenVNCWRAPPINVOKE.vncRfbRectangle_t_height_get(swigCPtr);
      return ret;
    } 
  }

  public vncRfbEncoding_t encoding_type {
    set {
      OpenVNCWRAPPINVOKE.vncRfbRectangle_t_encoding_type_set(swigCPtr, (int)value);
    } 
    get {
      vncRfbEncoding_t ret = (vncRfbEncoding_t)OpenVNCWRAPPINVOKE.vncRfbRectangle_t_encoding_type_get(swigCPtr);
      return ret;
    } 
  }

}

}
