/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.openvnc {

public enum vncRfbServerMsg_e {
  vncRfbServerMsg_FramebufferUpdate = 0,
  vncRfbServerMsg_SetColorMapEntries = 1,
  vncRfbServerMsg_Bell = 2,
  vncRfbServerMsg_ServerCutText = 3
}

}
