/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.openvnc {

public enum vncRfbEncoding_t {
  vncRfbEncoding_Raw = 0,
  vncRfbEncoding_CopyRect = 1,
  vncRfbEncoding_RRE = 2,
  vncRfbEncoding_Hextile = 5,
  vncRfbEncoding_ZRLE = 16
}

}
