/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.openvnc {

public enum vncRfbMsgType_t {
  vncRfbMsgType_None,
  vncRfbMsgType_ProtocolVersion,
  vncRfbMsgType_Security,
  vncRfbMsgType_VNCAuthChallenge,
  vncRfbMsgType_SecurityResult,
  vncRfbMsgType_ServerInit,
  vncRfbMsgType_FramebufferUpdate,
  vncRfbMsgType_SetColorMapEntries,
  vncRfbMsgType_Bell,
  vncRfbMsgType_ServerCutText,
  vncRfbMsgType_ClientInit,
  vncRfbMsgType_PointerEvent,
  vncRfbMsgType_KeyEvent,
  vncRfbMsgType_SetEncoding,
  vncRfbMsgType_SetPixelFormat,
  vncRfbMsgType_FramebufferUpdateRequest
}

}
