/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.openvnc {

public enum vncRfbVersion_t {
  vncRfbVersion_None = 0,
  vncRfbVersion_3_3,
  vncRfbVersion_3_7,
  vncRfbVersion_3_8,
  vncRfbVersion_3_5 = vncRfbVersion_3_3
}

}
