/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.openvnc {

public enum vncRfbSecurity_t {
  vncRfbSecurity_Invalid = 0,
  vncRfbSecurity_None = 1,
  vncRfbSecurity_VNC_Authentication = 2,
  vncRfbSecurity_RA2 = 5,
  vncRfbSecurity_RA2ne = 6,
  vncRfbSecurity_Tight = 16,
  vncRfbSecurity_Ultra = 17,
  vncRfbSecurity_TLS = 18,
  vncRfbSecurity_VeNCrypt = 19,
  vncRfbSecurity_GTK_VNC_SASL = 20,
  vncRfbSecurity_MD5 = 21,
  vncRfbSecurity_Colin_Dean_xvp = 22
}

}
